-- MySQL Script generated by MySQL Workbench
-- Wednesday 30 November 2022 10:31:56 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bhazi_test_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bhazi_test_db` ;

-- -----------------------------------------------------
-- Schema bhazi_test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bhazi_test_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bhazi_test_db` ;

-- -----------------------------------------------------
-- Table `bhazi_test_db`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`profile` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `email_id` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NULL DEFAULT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_rc7r62u5tals0tl5rkeyyo5sb` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `UK_c1dkiawnlj6uoe6fnlwd6j83j` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`address` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`address` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `delivery_time_preference` VARCHAR(20) NOT NULL,
  `floor` VARCHAR(20) NULL DEFAULT NULL,
  `full_address` VARCHAR(255) NOT NULL,
  `instruction` VARCHAR(50) NULL DEFAULT NULL,
  `lattitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `tag` VARCHAR(20) NULL DEFAULT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK9cm2xydhhkvra3wpnh90yb3y0` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `FK9cm2xydhhkvra3wpnh90yb3y0`
    FOREIGN KEY (`profile_id`)
    REFERENCES `bhazi_test_db`.`profile` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`charge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`charge` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`charge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `api` FLOAT NOT NULL,
  `delivery` FLOAT NOT NULL,
  `handling` FLOAT NOT NULL,
  `hosting` FLOAT NOT NULL,
  `network` FLOAT NOT NULL,
  `operation` FLOAT NOT NULL,
  `platform` FLOAT NOT NULL,
  `profit` FLOAT NOT NULL,
  `slippage` FLOAT NOT NULL,
  `timestamp` DATETIME(3) NULL DEFAULT NULL,
  `transport` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`delivery` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`delivery` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`order_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`order_history` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`order_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `amount` FLOAT NOT NULL,
  `coupon_balance` FLOAT NOT NULL,
  `delivery_charge` FLOAT NOT NULL,
  `delivery_time_preference` VARCHAR(20) NOT NULL,
  `delivery_type` VARCHAR(20) NOT NULL,
  `order_date` DATE NOT NULL,
  `packaging_charge` FLOAT NOT NULL,
  `packaging_type` VARCHAR(20) NOT NULL,
  `payable` FLOAT NULL DEFAULT NULL,
  `payment_mode` VARCHAR(20) NOT NULL,
  `referral_balance` FLOAT NULL DEFAULT NULL,
  `shop_id` TINYINT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `wallet_balance` FLOAT NULL DEFAULT NULL,
  `address_id` BIGINT NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK351ei5xl9j7a11lvs8ly2f2y4` (`address_id` ASC) VISIBLE,
  INDEX `FKfoh1fqdrldf7cuulqe6sinvnn` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `FK351ei5xl9j7a11lvs8ly2f2y4`
    FOREIGN KEY (`address_id`)
    REFERENCES `bhazi_test_db`.`address` (`id`),
  CONSTRAINT `FKfoh1fqdrldf7cuulqe6sinvnn`
    FOREIGN KEY (`profile_id`)
    REFERENCES `bhazi_test_db`.`profile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`product` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `base_price` INT NOT NULL,
  `base_quantity` VARCHAR(30) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `number_of_pieces` TINYINT NOT NULL,
  `out_of_stock` BIT(1) NOT NULL,
  `selling_price` INT NOT NULL,
  `sold_by_piece` VARCHAR(15) NOT NULL,
  `sub_type` VARCHAR(15) NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_jmivyxk9rmgysrmsqw15lqr5b` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`order_item` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `product_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp9gvajvai3ytifaflvln0brif` (`order_id` ASC) VISIBLE,
  INDEX `FKpu8m9ypwy9nyqya8pos70fdna` (`product_name` ASC) VISIBLE,
  CONSTRAINT `FKp9gvajvai3ytifaflvln0brif`
    FOREIGN KEY (`order_id`)
    REFERENCES `bhazi_test_db`.`order_history` (`id`),
  CONSTRAINT `FKpu8m9ypwy9nyqya8pos70fdna`
    FOREIGN KEY (`product_name`)
    REFERENCES `bhazi_test_db`.`product` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`referral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`referral` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`referral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` FLOAT NOT NULL,
  `income` FLOAT NOT NULL,
  `referral_code` VARCHAR(8) NOT NULL,
  `verified` BIT(1) NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ry9xvhv907b2ksmum81nvxvp7` (`profile_id` ASC) VISIBLE,
  UNIQUE INDEX `UK_q393lqb8smivq2k68shc6ovas` (`referral_code` ASC) VISIBLE,
  INDEX `FKolaa6b15w3kb0ebq0wc3qnsi2` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `FK2lkpogetqkwmlqjaccdtebp8u`
    FOREIGN KEY (`profile_id`)
    REFERENCES `bhazi_test_db`.`profile` (`id`),
  CONSTRAINT `FKolaa6b15w3kb0ebq0wc3qnsi2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `bhazi_test_db`.`referral` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`referral_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`referral_transaction` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`referral_transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `amount` FLOAT NOT NULL,
  `description` VARCHAR(32) NULL DEFAULT NULL,
  `status` BIT(1) NOT NULL,
  `referral_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1gxt45p89q1ur3bs6jfodmnpd` (`referral_id` ASC) VISIBLE,
  CONSTRAINT `FK1gxt45p89q1ur3bs6jfodmnpd`
    FOREIGN KEY (`referral_id`)
    REFERENCES `bhazi_test_db`.`referral` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`shop` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`shop` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `lattitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `tag` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_kmtoqn66a5h3w4c3vx9fenr4v` (`tag` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`transaction` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `amount` FLOAT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `payment_mode` VARCHAR(20) NOT NULL,
  `status` BIT(1) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK41ttw4iihxjwnjfj4cqmps7xv` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `FK41ttw4iihxjwnjfj4cqmps7xv`
    FOREIGN KEY (`profile_id`)
    REFERENCES `bhazi_test_db`.`profile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`wallet` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` FLOAT NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_hkwxwy7ytybldpfekxr1nv5tm` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `FK6csigaqw64a3ma4fpx73kammc`
    FOREIGN KEY (`profile_id`)
    REFERENCES `bhazi_test_db`.`profile` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bhazi_test_db`.`wallet_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bhazi_test_db`.`wallet_transaction` ;

CREATE TABLE IF NOT EXISTS `bhazi_test_db`.`wallet_transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `amount` FLOAT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `status` BIT(1) NOT NULL,
  `wallet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK6cnvafp3a0xhbs0eh9w26sett` (`wallet_id` ASC) VISIBLE,
  CONSTRAINT `FK6cnvafp3a0xhbs0eh9w26sett`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `bhazi_test_db`.`wallet` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
